id: P008011
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1660
  title: ཞི་ཁྲོ་ལྷ་ཚོགས་མཐོང་བ་ཀུན་གྲོལ།
  author: ''
  volumes:
    0b02e4e4e7a74cbb84444a064e16a527:
      image_group_id: I1KG1662
      title: ''
      volume_number: 1
      total_pages: 136
ebook_metadata:
  title: ཞི་ཁྲོ་ལྷ་ཚོགས་མཐོང་བ་ཀུན་གྲོལ།
  author: ''
  sku: P008011
  cover: cover.jpg
  layers:
  - pagination
